title: Comparative SICR Protest Modelling
author: Thijs van der Meer
logo: ""

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/thijsvndmeer/protest-sicr
  branch: main

html:
  use_issues_button: false
  use_repository_button: true
  use_edit_page_button: false

sphinx:
  config:
    html_show_copyright: false
    exclude_patterns:
      - "README.md"
      - "venv/*"
      - "_build/*"
      - "data/*"
      - "results/*"
      - ".github/*"
